# Generated by Django 2.2.1 on 2020-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
