# Generated by Django 2.2.1 on 2020-03-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
